version: '3.6'

# For sadeaf-worker testing only

services:
  localstack:
    image: localstack/localstack:0.11.4
    ports:
      - "24566:4566"
    environment:
      - SERVICES=s3,sqs,ses
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=accessKeyId
      - AWS_SECRET_ACCESS_KEY=secretAccessKey

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "21025:1025"
      - "28025:8025"
