version: '3.6'

# Single docker-compose.yml for the entire project for a more consistent single source of truth.
# For ports that will collide with dev, a '1' is prefixed the the original port number.

# Development Note: Docker containers are immutable docker image,
# if you updated any of the content within the docker images you need to rebuild the docker image.
# You can do so via this command docker-compose up --build

services:
  localstack:
    image: localstack/localstack:0.11.4
    ports:
      - "4566:4566"
      - "8888:8888"
    environment:
      - SERVICES=s3
      - PORT_WEB_UI=8888
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=accessKeyId
      - AWS_SECRET_ACCESS_KEY=secretAccessKey

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "11025:1025"
      - "18025:8025"

  postgres:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: sadeaf_app
    volumes:
      - "./docker-postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh"

  sadeaf-hasura:
    build: sadeaf-hasura
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/sadeaf_app
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      WEB_HOOK_URL: http://host.docker.internal:3000

#  sadeaf-web:
#    build: sadeaf-web
#    ports:
#      - "13000:3000"
#    depends_on:
#      - sadeaf-hasura
#      - localstack
#    environment:
#      SVC_SADEAF_HASURA_URL: http://sadeaf-hasura:8080
#
#      SMTP_HOST: mailhog
#      SMTP_PORT: 1025
#
#      AWS_REGION: us-east-1
#      AWS_ACCESS_KEY_ID: accessKeyId
#      AWS_SECRET_ACCESS_KEY: secretAccessKey
#
#      POSTGRES_QUEUE_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/sadeaf_worker
      # TODO(fuxing): To be implemented: Cognito
