version: '3.6'

# Single docker-compose.yml for the entire project for a more consistent single source of truth.
# For ports that will collide with dev, a '1' is prefixed the the original port number.

# Development Note: Docker containers are immutable docker image,
# if you updated any of the content within the docker images you need to rebuild the docker image.
# You can do so via this command docker-compose up --build

services:
  postgres:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: sadeaf_app

  sadeaf-hasura:
    build: sadeaf-hasura
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/sadeaf_app
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
