version: 2
endpoint: http://localhost:8080
metadata_directory: metadata
migrations_directory: migrations
show_update_notification: false
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
admin_secret: sadeaf-hasura-console
