name: Pull request to master, sadeaf-api

on:
  pull_request:
    branches:
      - master
    paths:
      - 'sadeaf-api/**'
      - '!sadeaf-api/tests/**'
      - '!sadeaf-api/**.md'

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          path: sadeaf-api
          registry: docker.pkg.github.com
          repository: SADEAFxSMU/sadeaf-app/sadeaf-api
          tags: latest
          push: false

  run_yarn_test:
    name: Run yarn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: yarn install
        working-directory: sadeaf-api

      - run: yarn test
        working-directory: sadeaf-api
