name: sadeaf-web pr to master

on:
  pull_request:
    branches:
      - master
    paths:
      - 'sadeaf-web/**'

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          path: sadeaf-web
          registry: docker.pkg.github.com
          repository: sadeafxsmu/sadeaf-app/sadeaf-web
          tags: latest
          push: false

  run_yarn_test:
    name: Run yarn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: yarn install
        working-directory: sadeaf-web

      - run: yarn test
        working-directory: sadeaf-web
